### ISSUE TITLE
Score becomes blank during attempt to click on it

### ISSUE THREAD

**Issue by topchyan** [jwdj/EasyABC#102]
Attached is a screen recording showing the issue. This was noted in more recent versions of the components.

https://github.com/user-attachments/assets/df8e0740-1c1c-4776-bd48-babfa9de8c0b

**Comment by revad** [comment]
This was solved by the proposed solution to #77 and #90. Try these changes (make backups before editing).

In easy_abc.py replace the function GetAbcToPlay with this:
```
    def GetAbcToPlay(self):

#SMB Helper funtion to return end_offset in a note given start_offset [SMB] 2024-03
        def _get_end_offset(note_offset):
            for (start_offset, end_offset, _) in notes:
                if start_offset == note_offset:
                    break
            return(end_offset)

        tune = self.GetSelectedTune()
        if tune:
            position, end_position = tune.offset_start, tune.offset_end
            if end_position > position and len(self.selected_note_descs) > 2: ## and False:
                text = self.editor.GetTextRange(position, end_position)
                notes = get_notes_from_abc(text)
                num_header_lines, first_note_line_index = self.get_num_extra_header_lines(tune)

                # workaround for the fact the abcm2ps returns incorrect row numbers
                # check the row number of the first note and if it doesn't agree with the actual value
                # then pretend that we have more or less extra header lines
                if self.music_pane.current_page.notes: # 1.3.6.2 [JWdJ] 2015-02
                    actual_first_row = self.music_pane.current_page.notes[0][2]-1
                    correction = (actual_first_row - first_note_line_index)
                    num_header_lines += correction

                temp = text.replace('\r\n', ' \n').replace('\r', '\n')  # re.sub(r'\r\n|\r', '\n', text)
                line_start_offset = [m.start(0) for m in re.finditer(r'(?m)^', temp)]

                selected_note_offsets = []
                for (_, _, abc_row, abc_col, desc) in self.selected_note_descs:
                    abc_row -= num_header_lines
                    selected_note_offsets.append(line_start_offset[abc_row-1]+abc_col)

#SMB parse selected_notes list looking for chords [SMB] 2024-03
                selected_note_offsets.sort()                
                i = 0
                while i < len(selected_note_offsets):
                    note_offset = selected_note_offsets[i]
                    if text[note_offset] == '[':
                        chord = True
                        note_offset += 1
                        while chord == True and i < len(selected_note_offsets):
                            selected_note_offsets[i] = note_offset
                            end_offset = _get_end_offset(note_offset)
                            note_offset = end_offset
                            chord = text[note_offset] != ']'
                            if chord == True:
                                i += 1
                    i += 1

                unselected_note_offsets = [(start_offset, end_offset) for (start_offset, end_offset, _) in notes if not any(p for p in selected_note_offsets if start_offset <= p < end_offset)]
                unselected_note_offsets.sort()
                pieces = []
                pos = 0
                for start_offset, end_offset in unselected_note_offsets:
                    if start_offset > pos:
                        pieces.append(text[pos:start_offset])
                    pieces.append(' ' * (end_offset - start_offset))
                    pos = end_offset
                pieces.append(text[pos:])
                text = ''.join(pieces)

                # for some strange reason the MIDI sequence seems to be cut-off in the end if the last note is short
                # adding a silent extra note seems to fix this
#DR3
#                text = text + os.linesep + '%%MIDI control 7 0' + os.linesep + 'A2'

                return (tune, text)
            return (tune, self.editor.GetTextRange(position, end_position))
        return (tune, '')
```
In svrenderer.py replace the function select_notes with this:
```
    def select_notes(self, selection_rect):
        in_selection = selection_rect.Contains
#DR2        selected_offsets = set((abc_row, abc_col) for (int(x), int(y), int(abc_row), int(abc_col), desc) in self.notes if in_selection((x, y)))
        selected_offsets = set((abc_row, abc_col) for (x, y, abc_row, abc_col, desc) in self.notes if in_selection((int(x), int(y))))
        list_of_sets = [self.indices_per_row_col[row][col] for row, col in selected_offsets]
        selected_indices = set().union(*list_of_sets)
#DR1        if selected_indices:
#DR1            selected_indices = set(range(min(selected_indices), max(selected_indices), + 1))       
        self.selected_indices = selected_indices
        self.selected_indices = selected_indices
        return selected_indices

```
In music_score_panel.py replace the function draw_drag_rect with this:
```
    def draw_drag_rect(self, dc):
        if self.drag_rect:
            dc = wx.GraphicsContext.Create(dc)
            #z = self.renderer.zoom
            #dc.Scale(z, z)
            x, y, width, height = self.drag_rect
#DR1            dc.SetPen( dc.CreatePen(wx.Pen(wx_colour('black'), 1.0, style=wx.DOT )) )
            dc.SetPen( dc.CreatePen(wx.Pen(wx_colour('black'), 1, style=wx.DOT )) ) 
            dc.SetBrush(dc.CreateBrush(wx.Brush(wx_colour('#fffbc6'), wx.SOLID)))
            path = dc.CreatePath()
            path.MoveToPoint(x, y)
            path.AddLineToPoint(x+width, y)
            path.AddLineToPoint(x+width, y+height)
            path.AddLineToPoint(x, y+height)
            path.AddLineToPoint(x, y)
            dc.DrawPath(path)
```
Please report whether that works for you. If they work I invite you to also test the changes in #91. 

These changes need more testing so please report anything that appears not to work. 

I am using OpenSuSE TW Linux and Python 3.11 or 3.13. I may not have the same versions of the programs in abcMIDI as you - it's a community packaged (abcMIDI-2022.12.30-15.23.x86_64.rpm)

**Comment by topchyan** [comment]
I applied patches and here's what it looks like: highlighting score now highlights corresponding ABC and no longer blinks, which is great! However highlighting ABC doesn't yet highlight notes in the score and the "follow the score" feature still doesn't seem to be available. But thank you for following up on this bug!

https://github.com/user-attachments/assets/b9e47dc9-b649-4098-9236-43b830de3f11

**Comment by topchyan** [comment]
For testing I stick with the latest available abcmidi, which I build on the fly every time I install EasyABC, just in case. I'm on Linux Mint (LMDE 6) and still try to run Python (3.13.1) via pyenv, since it is more convenient for me to play with different scenarios that way.

**Comment by topchyan** [comment]
Basically, this commit of abcmidi was the last when "follow the score" still worked. I also mentioned microtones there which are now working in the most current version of abcmidi as of this writing. But "follow the score" somehow isn't. I didn't know whether that's a limitation of EasyABC or abcmidi or perhaps both since they are intertwined.  

https://github.com/sshlien/abcmidi/commit/9b419e0128eb0895c806760b13bdea9c10e9a0dc

**Comment by aupfred** [comment]
Hi,
@revad I do not have the changes you mentioned on def GetAbcToPlay(self) and the issue is not present related to the topic.

@topchyan Can you tell on which version you've seen the selection of ABC code that highlights the note in musicscore?
I know I had issues with the highlight however I think I've only seen it the other way round: selecting notes in musicscore via a rectangle area selection, will highlight the corresponding ABC notes in the editor.
Also clicking in the ABC editor close to an ABC note will highlight the closest note on musicscore.

**Comment by revad** [comment]
@aupfred Yes, the changes to svrenderer.py and music_score_panel.py solve the immediate problem - the inability to select a piece of score. But I find that doesn't allow it to play.

The changes to easy_abc.py I proposed do allow it to play (and with >1 voice) as @topchyan has confirmed. They may not be optimum - and the DR3 one which comes from https://github.com/jwdj/EasyABC/issues/90#issuecomment-2045585028 really needs investigation.

**Comment by aupfred** [comment]
@revad on my side without the other changes it plays, at least on Mac. I'll do some other tests on other OS.
To be noted, I haven't yet included the other changes to add the chord or to select multi-voices.

**Comment by revad** [comment]
@aupfred  I retested with just the float>integer changes and with this tune:

X: 1
T:Constant Billy
M:6/8
L:1/8
K:G
D|"G"G2d B3/2G/2B|"Am"c2A "D7"F2D|"G"B3/2A/2G"C"E2D|"D7"D3/2E/2F"G"G2

If the tune ends without a newline (which my previous tests all did) a selection will not play. If there is a blank line after it, it will. 

The ABC spec says "An abc tune [is] terminated by an empty line or the end of the file."

This looks superficially like the problem identified in https://github.com/jwdj/EasyABC/issues/90#issuecomment-2045585028

I also testing in Windows 11. It's the same.

**Comment by aupfred** [comment]
@revad OK tested here and I was able to play.

For instance it generated the following file here with selection of the notes in a measure

X: 1
%%MIDI program 1 0
%%MIDI program 2 0
%%MIDI program 3 0
%%MIDI program 4 0
%%MIDI program 5 0
%%MIDI program 6 0
%%MIDI program 7 0
%%MIDI program 8 0
%%MIDI program 9 0
%%MIDI program 10 0
%%MIDI program 11 0
%%MIDI program 12 0
%%MIDI program 13 0
%%MIDI program 14 0
%%MIDI program 15 0
%%MIDI program 16 0
%%MIDI program 0
%%MIDI gchordon
%%MIDI program 0
%%MIDI chordprog 24
%%MIDI bassprog 32
%%MIDI chordvol 44
%%MIDI bassvol 44
Q:1/4 =120
T:Constant Billy
M:6/8
L:1/8
K:G
%%MIDI control 7 96
 |"G"            |"Am"c2A "D7"F2D|"G"        "C"   |"D7"        "G"  
%%MIDI control 7 0
A2

Will double check, maybe one of the changes I'm working on for the midi playback on Mac has changed something.
Or the version of abcmidi

**Comment by aupfred** [comment]
OK, found something odd.
If in the EasyABC settings, in abc2midi I have the play gchord option chosen, then selection is played. If not selection is not played...
Same behavior on Mac and on a newly installed Debian in virtualbox

I'll look further
